# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96c671c60617fa9200cd4d0fa1376d14cacda0cd343f1d12617c989b583c5f9d65156cd47a226d1914a720da858448ec9303b4348240898fd6a793d462efdb1

test:
  secret_key_base: 59e097fa55acc31ddf7cf2167d54cf55e2fb24208557510c8a71fd13bf0f467c85a112b7b2de3717357f7a0d6a329d7c8d9ad7210a7589f46611c6c4c5924c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
